"""posts-table

Revision ID: 44f52e571a73
Revises: f0000eb70080
Create Date: 2019-07-19 03:17:15.294465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f52e571a73'
down_revision = 'f0000eb70080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_username', table_name='posts')
    op.create_index(op.f('ix_posts_username'), 'posts', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_username'), table_name='posts')
    op.create_index('ix_posts_username', 'posts', ['username'], unique=1)
    # ### end Alembic commands ###
