"""posts table

Revision ID: f0000eb70080
Revises: 152d99d1dc75
Create Date: 2019-07-11 21:16:32.035171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0000eb70080'
down_revision = '152d99d1dc75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_posts_username'), 'posts', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_username'), table_name='posts')
    op.drop_column('posts', 'username')
    # ### end Alembic commands ###
